language: java

addons:
  apt:
    packages: oracle-java8-installer

sudo: required

matrix:
  include:
    # Custom builds
#    - os: linux
#      jdk: oraclejdk8
#      env: TOKEN=nogui
#      script: mvn test -B -Dtest=commandline/*Test.java,implementationchecker/*Test.java
#    - os: linux
#      jdk: oraclejdk8
#      env: TOKEN=gui
#      script: mvn test -B -Dtest=gui/*Test.java
    - os: osx
      env: OS=osx
      script: ls -l
  exclude:
    # Exclude default build
    - jdk: oraclejdk8

before_install:
  - if [ "${TOKEN}" != "nogui" ]; then export DISPLAY=:99.0; fi
  - if [ "${TOKEN}" != "nogui" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$OS" == "osx" ]]
  - then
  -   echo "Line 1"
  -   sudo ls -lisa
  -   echo "Line 2"
  - fi