language: java

addons:
  apt:
    packages: oracle-java8-installer

sudo: required

matrix:
  include:
    # Custom builds
#    - os: linux
#      jdk: oraclejdk8
#      env: TOKEN=nogui
#      script: mvn test -B -Dtest=commandline/*Test.java,implementationchecker/*Test.java
#    - os: linux
#      jdk: oraclejdk8
#      env: TOKEN=gui
#      script: mvn test -B -Dtest=gui/*Test.java
    - os: osx
      env: OS=osx
      script: ls -l
  exclude:
    # Exclude default build
    - jdk: oraclejdk8

before_install:
  - if [ "${TOKEN}" == "gui" ]; then export DISPLAY=:99.0; fi
  - if [ "${TOKEN}" == "gui" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${OS}" == "osx" ]; then sudo ls -l; fi
  - if [ "${OS}" == "osx" ]; then sudo ls -lR; fi
  - if [ "${OS}" == "osx" ];
    then
      echo "Line 1";
      echo "Line 2";
    fi
